### ISSUE TITLE
[Feature Request] Disable Sidebar Hover

### ISSUE THREAD

**Issue by noxhirsch** [maykar/compact-custom-header#166]
**Is your feature request related to a problem? Please describe.**
It is pretty annoying that the whole sidebar opens when you accidentally hover it. You have to move the cursor "far" to the right to close it again. Even if you open the sidebar intentionally it looks not very elegant.
**Describe the solution you'd like**
It would be great to have a feature to disable the sidebar hover, so you only have the icons in the sidebar.

----------
By the way: Thank you very much for your amazing addon! This makes HA so much nicer! These features should be integrated into HA :/

**Comment by maykar** [comment]
Since CCH only operates inside of Lovelace I need to keep any modification of the sidebar to a minimum. The sidebar is required for navigation outside of Lovelace, so any modification of it should be handled with an addon that is available across the entire frontend. Something like this doesn't exist yet, but I'm sure it will in time.
