### ISSUE TITLE
[Feature Request] - Hide tab but manually navigate to it

### ISSUE THREAD

**Issue by 4meuwil** [maykar/compact-custom-header#76]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I use browser commander to take blue iris triggers/scripts to command all browsers to change to that camera (iframe) and then afterwards back home...works great. BUT, I was hoping that I could hide the tabs from the normal interface header but still be able to navigate to them via path. Seems as though any hidden tabs just send you home when trying to get them manually via path.

**Additional Context**

**Comment by 4meuwil** [comment]
I could see this as security feature preventing users from accessing tabs you don't want them to. For now, my solution was using `title: ' '` and no icon on each view and placing them at the end.

**Comment by maykar** [comment]
The reason the redirect exists is so that if you're hiding your first tab you don't want it to show when you navigate to /lovelace/, so it looks for the next non-hidden tab and navigates to it. This also helps keep hidden tabs hidden from users.

I can see how turning this off could be helpful. I'll make it a config option so you can toggle the redirect.

**Comment by 4meuwil** [comment]
That would be great, potentially having two options, secure completely by using the redirect, and hide only allowing manual navigation.

**Comment by maykar** [comment]
Config option for redirect has been added in 1.0.1b7

**Comment by 4meuwil** [comment]
Thank You!
